In [1]:
require 'torch'
require 'cutorch'
require 'nn'
require 'nnx'
require 'optim'
require 'image'
require 'dataset-mnist'
require 'pl'
require 'paths'

In [2]:
torch.setnumthreads(4)

In [3]:
classes = {'1','2','3','4','5','6','7','8','9','10'}
geometry = {32,32}

### Define model

In [4]:
--torch.setdefaulttensortype("torch.FloatTensor")

In [5]:
require 'cunn'

true	


In [6]:
model = nn.Sequential()
model:add(nn.Reshape(32*32, true))
model:add(nn.Linear(32*32, 10))

In [7]:
parameters,gradParameters = model:getParameters()

In [8]:
criterion = nn.MultiMarginCriterion()

In [9]:
nbTrainingPatches = 60000
nbTestingPatches = 10000

In [10]:
trainData = mnist.loadTrainSet(nbTrainingPatches, geometry)
trainData:normalizeGlobal(mean, std)

<mnist> done	


In [11]:
testData = mnist.loadTestSet(nbTestingPatches, geometry)
testData:normalizeGlobal(mean, std)

<mnist> done	


In [12]:
confusion = optim.ConfusionMatrix(classes)

In [13]:
trainLogger = optim.Logger(paths.concat('train.log'))
testLogger = optim.Logger(paths.concat('test.log'))
finalLogger = optim.Logger(paths.concat('predictions.log'))

In [14]:
batchSize = 100
coefL1 = 0
coefL2 = 0

In [15]:
-- training function
function train(dataset)
   -- epoch tracker
   epoch = epoch or 1

   -- local vars
   local time = sys.clock()

   -- do one epoch
   print('<trainer> on training set:')
   print("<trainer> online epoch # " .. epoch .. ' [batchSize = ' .. batchSize .. ']')
   for t = 1,dataset:size(),batchSize do
      -- create mini batch
      local inputs = torch.Tensor(batchSize,1,geometry[1],geometry[2])
      local targets = torch.Tensor(batchSize)
      local k = 1
      for i = t,math.min(t+batchSize-1,dataset:size()) do
         -- load new sample
         local sample = dataset[i]
         local input = sample[1]:clone()
         local _,target = sample[2]:clone():max(1)
         target = target:squeeze()
         inputs[k] = input
         targets[k] = target
         k = k + 1
      end

      -- create closure to evaluate f(X) and df/dX
      local feval = function(x)
         -- just in case:
         collectgarbage()

         -- get new parameters
         if x ~= parameters then
            parameters:copy(x)
         end

         -- reset gradients
         gradParameters:zero()

         -- evaluate function for complete mini batch
         local outputs = model:forward(inputs)
         local f = criterion:forward(outputs, targets)

         -- estimate df/dW
         local df_do = criterion:backward(outputs, targets)
         model:backward(inputs, df_do)

         -- penalties (L1 and L2):
         if coefL1 ~= 0 or coefL2 ~= 0 then
            -- locals:
            local norm,sign= torch.norm,torch.sign

            -- Loss:
            f = f + coefL1 * norm(parameters,1)
            f = f + coefL2 * norm(parameters,2)^2/2

            -- Gradients:
            gradParameters:add( sign(parameters):mul(coefL1) + parameters:clone():mul(coefL2) )
         end

         -- update confusion
         for i = 1,batchSize do
            confusion:add(outputs[i], targets[i])
         end

         -- return f and df/dX
         return f,gradParameters
      end

      -- optimize on current mini-batch


     -- Perform SGD step:
     sgdState = sgdState or {
        learningRate = .03,
        momentum = 0,
        learningRateDecay = 5e-7
     }
     optim.sgd(feval, parameters, sgdState)

     -- disp progress
     xlua.progress(t, dataset:size())


   end
   
   -- time taken
   time = sys.clock() - time
   time = time / dataset:size()
   print("<trainer> time to learn 1 sample = " .. (time*1000) .. 'ms')

   -- print confusion matrix
   print(confusion)
   trainLogger:add{['% mean class accuracy (train set)'] = confusion.totalValid * 100}
   confusion:zero()

   -- save/log current net
   local filename = paths.concat('mnist.net')
   os.execute('mkdir -p ' .. sys.dirname(filename))
   if paths.filep(filename) then
      os.execute('mv ' .. filename .. ' ' .. filename .. '.old')
   end
   print('<trainer> saving network to '..filename)
   -- torch.save(filename, model)

   -- next epoch
   epoch = epoch + 1
end

In [1]:
finalLogger:setNames{'training error', 'test error'}
-- test function
function test(dataset, flag)
   -- local vars
   local time = sys.clock()

   -- test over given dataset
   print('<trainer> on testing Set:')
   for t = 1,dataset:size(),batchSize do
      -- disp progress
      xlua.progress(t, dataset:size())

      -- create mini batch
      local inputs = torch.Tensor(batchSize,1,geometry[1],geometry[2])
      local targets = torch.Tensor(batchSize)
      local k = 1
      for i = t,math.min(t+batchSize-1,dataset:size()) do
         -- load new sample
         local sample = dataset[i]
         local input = sample[1]:clone()
         local _,target = sample[2]:clone():max(1)
         target = target:squeeze()
         inputs[k] = input
         targets[k] = target
         k = k + 1
      end

      -- test samples
      local preds = model:forward(inputs)

      -- confusion:
      for i = 1,batchSize do
         confusion:add(preds[i], targets[i])
--          if flag==true then finalLogger:add{preds[i],targets[i]} end
      end
   end

   -- timing
   time = sys.clock() - time
   time = time / dataset:size()
   print("<trainer> time to test 1 sample = " .. (time*1000) .. 'ms')

   -- print confusion matrix
   print(confusion)
   testLogger:add{['% mean class accuracy (test set)'] = confusion.totalValid * 100}
    confusion:zero()
end

----------------------------------------------------------------------


In [17]:
i = 0
while (i<10) do
   -- train/test
   train(trainData)
    test(testData)
   i = i + 1
   -- plot errors

      trainLogger:style{['% mean class accuracy (train set)'] = '-'}
      testLogger:style{['% mean class accuracy (test set)'] = '-'}
      trainLogger:plot()
      testLogger:plot()
end

<trainer> on training set:	
<trainer> online epoch # 1 [batchSize = 100]	


Progress: 54401 / 60000	


<trainer> time to learn 1 sample = 0.064350247383118ms	


ConfusionMatrix:
[[    5555       1      50      21      22     139      56      13      55      11]   93.787% 	[class: 1]
 [       2    6409      39      57       5      50      13      18     138      11]   95.061% 	[class: 2]
 [      66      70    5013     119     143      38     131     109     220      49]   84.139% 	[class: 3]
 [      41      50     152    5164      13     340      45      66     181      79]   84.228% 	[class: 4]
 [      14      32      60       9    5215      17      61      27      54     353]   89.267% 	[class: 5]
 [      89      47      65     288     132    4393     112      32     159     104]   81.037% 	[class: 6]
 [      52      29      83       7      92     101    5485       7      57       5]   92.683% 	[class: 7]
 [      49      62     108      42     103      14       6    5553      21     307]   88.635% 	[class: 8]
 [      33     167     105     186      38     253      37      30    4861     141]   83.080% 	[class: 9]
 [      61      51      37   

<trainer> saving network to /home/saurabh/Desktop/COGS 260/Project 2/saurabh/torch tutorial/Assignment 2/mnist.net	
<trainer> on testing Set:	


<trainer> time to test 1 sample = 0.043629097938538ms	
ConfusionMatrix:
[[     948       0       1       2       0      19       7       1       2       0]   96.735% 	[class: 1]
 [       0    1108       2       2       0       2       4       2      15       0]   97.621% 	[class: 2]
 [      12      15     878      17      21      11      18      14      40       6]   85.078% 	[class: 3]
 [       7       1      19     865       1      76       1      14      14      12]   85.644% 	[class: 4]
 [       3       4       4       1     897       4      10       1       4      54]   91.344% 	[class: 5]
 [       8       4       4      23       5     808      13       3      14      10]   90.583% 	[class: 6]
 [      14       3       4       1      13      34     887       1       1       0]   92.589% 	[class: 7]
 [       3      10      24       6       7       4       0     908       3      63]   88.327% 	[class: 8]
 [       8      14       8      25       8      76      11       7     791      

 _targ_idx : LongTensor - empty
  averageValid : 0.89922035336494
  classes : 
    {
      1 : 1
      2 : 2
      3 : 3
      4 : 4
      5 : 5
      6 : 6
      7 : 7
      8 : 8
      9 : 9
      10 : 10
    }
  _prediction : FloatTensor - size: 10
  _pred_idx : LongTensor - size: 1
  nclasses : 10
  _max : FloatTensor - size: 1
  _target : FloatTensor - empty
  unionvalids : FloatTensor - size: 10
  totalValid : 0.8999
}
<trainer> on training set:	
<trainer> online epoch # 2 [batchSize = 100]	


Progress: 49201 / 60000	


<trainer> time to learn 1 sample = 0.062403786182404ms	


ConfusionMatrix:
[[    5674       1      34      14      15      89      43       6      41       6]   95.796% 	[class: 1]
 [       2    6507      28      32       7      36       7      17      94      12]   96.514% 	[class: 2]
 [      45      66    5200     103     123      32     101      90     174      24]   87.278% 	[class: 3]
 [      25      40     125    5346       4     278      29      72     144      68]   87.196% 	[class: 4]
 [       7      24      43       9    5390       6      55      15      41     252]   92.263% 	[class: 5]
 [      74      41      55     220      79    4608      96      24     156      68]   85.003% 	[class: 6]
 [      40      19      63       5      86      95    5580       2      28       0]   94.289% 	[class: 7]
 [      26      33     103      24      71      11       3    5759      15     220]   91.923% 	[class: 8]
 [      33     130      79     156      31     204      42      21    5054     101]   86.378% 	[class: 9]
 [      39      35      24   

<trainer> saving network to /home/saurabh/Desktop/COGS 260/Project 2/saurabh/torch tutorial/Assignment 2/mnist.net	
<trainer> on testing Set:	


<trainer> time to test 1 sample = 0.035649704933167ms	
ConfusionMatrix:
[[     952       0       2       1       0      17       6       1       1       0]   97.143% 	[class: 1]
 [       0    1108       2       2       0       2       3       2      16       0]   97.621% 	[class: 2]
 [      12      14     890      16      16      11      14      12      41       6]   86.240% 	[class: 3]
 [       6       1      17     865       0      79       1      15      14      12]   85.644% 	[class: 4]
 [       1       2       4       1     907       4      10       2       4      47]   92.363% 	[class: 5]
 [       9       2       4      21       4     812      11       4      17       8]   91.031% 	[class: 6]
 [      13       3       6       1      15      37     881       1       1       0]   91.962% 	[class: 7]
 [       4       8      21       7       6       4       0     918       4      56]   89.300% 	[class: 8]
 [       9      12       7      21       8      70       8       9     810      

  averageValid : 0.90544720888138
  classes : 
    {
      1 : 1
      2 : 2
      3 : 3
      4 : 4
      5 : 5
      6 : 6
      7 : 7
      8 : 8
      9 : 9
      10 : 10
    }
  _prediction : FloatTensor - size: 10
  _pred_idx : LongTensor - size: 1
  nclasses : 10
  _max : FloatTensor - size: 1
  _target : FloatTensor - empty
  unionvalids : FloatTensor - size: 10
  totalValid : 0.9061
}


<trainer> on training set:	
<trainer> online epoch # 3 [batchSize = 100]	


Progress: 41601 / 60000	


<trainer> time to learn 1 sample = 0.067677998542786ms	


ConfusionMatrix:
[[    5676       1      33      13      14      88      45       8      40       5]   95.830% 	[class: 1]
 [       2    6517      28      30       7      35       6      18      88      11]   96.663% 	[class: 2]
 [      42      64    5235     100     116      31      95      83     170      22]   87.865% 	[class: 3]
 [      20      39     119    5403       4     261      28      63     136      58]   88.126% 	[class: 4]
 [       9      25      42       7    5418       5      55      14      37     230]   92.742% 	[class: 5]
 [      72      39      55     212      69    4640     100      22     148      64]   85.593% 	[class: 6]
 [      39      17      63       4      78      87    5599       3      27       1]   94.610% 	[class: 7]
 [      25      28      88      26      67      10       2    5797      15     207]   92.530% 	[class: 8]
 [      30     122      76     152      28     193      42      22    5093      93]   87.045% 	[class: 9]
 [      33      33      25   

<trainer> saving network to /home/saurabh/Desktop/COGS 260/Project 2/saurabh/torch tutorial/Assignment 2/mnist.net	
<trainer> on testing Set:	


<trainer> time to test 1 sample = 0.03378541469574ms	


ConfusionMatrix:
[[     950       0       3       1       0      17       7       1       1       0]   96.939% 	[class: 1]
 [       0    1108       2       2       0       2       3       2      16       0]   97.621% 	[class: 2]
 [      12      14     895      15      14      10      15      11      41       5]   86.725% 	[class: 3]
 [       5       1      18     871       0      72       1      14      15      13]   86.238% 	[class: 4]
 [       1       2       6       1     901       5      10       2       6      48]   91.752% 	[class: 5]
 [       9       2       4      22       4     810      12       5      18       6]   90.807% 	[class: 6]
 [      13       3       7       1      13      39     879       2       1       0]   91.754% 	[class: 7]
 [       3       9      19       7       6       3       0     924       5      52]   89.883% 	[class: 8]
 [       9      12       6      19       8      73       7      10     814      16]   83.573% 	[class: 9]
 [      11       7       1   

<trainer> on training set:	
<trainer> online epoch # 4 [batchSize = 100]	


Progress: 38001 / 60000	


<trainer> time to learn 1 sample = 0.060415069262187ms	


ConfusionMatrix:
[[    5690       1      33      13      13      84      45       7      33       4]   96.066% 	[class: 1]
 [       2    6532      27      26       7      33       5      17      81      12]   96.885% 	[class: 2]
 [      35      63    5266      97     110      32      89      82     164      20]   88.385% 	[class: 3]
 [      21      33     120    5413       5     253      27      63     140      56]   88.289% 	[class: 4]
 [       9      27      41       6    5429       4      57      16      35     218]   92.931% 	[class: 5]
 [      68      36      55     200      66    4676      98      22     141      59]   86.257% 	[class: 6]
 [      40      17      62       3      73      84    5609       3      26       1]   94.779% 	[class: 7]
 [      24      23      85      25      63      10       2    5826      15     192]   92.993% 	[class: 8]
 [      31     119      71     155      28     184      43      21    5110      89]   87.335% 	[class: 9]
 [      31      32      22   

<trainer> saving network to /home/saurabh/Desktop/COGS 260/Project 2/saurabh/torch tutorial/Assignment 2/mnist.net	
<trainer> on testing Set:	


<trainer> time to test 1 sample = 0.032224607467651ms	
ConfusionMatrix:
[[     948       0       3       1       0      19       7       1       1       0]   96.735% 	[class: 1]
 [       0    1109       2       2       0       3       3       2      14       0]   97.709% 	[class: 2]
 [       9      12     904      15      13      10      15      10      39       5]   87.597% 	[class: 3]
 [       4       1      18     877       0      68       1      13      16      12]   86.832% 	[class: 4]
 [       1       2       7       1     899       4      10       2       6      50]   91.548% 	[class: 5]
 [       9       2       4      22       4     811      10       5      19       6]   90.919% 	[class: 6]
 [      12       3       7       1      14      38     880       2       1       0]   91.858% 	[class: 7]
 [       3       9      20       7       5       2       0     928       3      51]   90.272% 	[class: 8]
 [       8      10       5      20       9      67       7       9     823      

      3 : 3
      4 : 4
      5 : 5
      6 : 6
      7 : 7
      8 : 8
      9 : 9
      10 : 10
    }
  _prediction : FloatTensor - size: 10
  _pred_idx : LongTensor - size: 1
  nclasses : 10
  _max : FloatTensor - size: 1
  _target : FloatTensor - empty
  unionvalids : FloatTensor - size: 10
  totalValid : 0.911
}


<trainer> on training set:	
<trainer> online epoch # 5 [batchSize = 100]	


Progress: 34601 / 60000	


<trainer> time to learn 1 sample = 0.063206919034322ms	


ConfusionMatrix:
[[    5707       1      30      11      13      75      42       7      32       5]   96.353% 	[class: 1]
 [       2    6532      28      25       7      32       4      19      81      12]   96.885% 	[class: 2]
 [      34      60    5277      95     107      27      86      83     170      19]   88.570% 	[class: 3]
 [      22      32     117    5434       4     248      24      62     135      53]   88.632% 	[class: 4]
 [       8      25      41       5    5448       5      57      17      34     202]   93.256% 	[class: 5]
 [      70      35      55     193      65    4689      92      23     142      57]   86.497% 	[class: 6]
 [      39      16      62       3      69      80    5619       3      26       1]   94.948% 	[class: 7]
 [      24      19      84      22      59      10       2    5841      14     190]   93.232% 	[class: 8]
 [      32     116      73     152      29     174      45      21    5124      85]   87.575% 	[class: 9]
 [      32      33      22   

<trainer> saving network to /home/saurabh/Desktop/COGS 260/Project 2/saurabh/torch tutorial/Assignment 2/mnist.net	
<trainer> on testing Set:	


<trainer> time to test 1 sample = 0.032843995094299ms	


ConfusionMatrix:
[[     950       0       3       1       0      18       6       1       1       0]   96.939% 	[class: 1]
 [       0    1109       2       2       0       3       3       2      14       0]   97.709% 	[class: 2]
 [       9      12     904      15      10      11      16      10      40       5]   87.597% 	[class: 3]
 [       4       1      18     874       0      71       1      14      16      11]   86.535% 	[class: 4]
 [       1       2       7       1     897       4      10       3       7      50]   91.344% 	[class: 5]
 [       8       2       4      19       4     818      10       4      17       6]   91.704% 	[class: 6]
 [      12       3       7       1      12      38     882       2       1       0]   92.067% 	[class: 7]
 [       2       9      20       7       5       2       0     931       3      49]   90.564% 	[class: 8]
 [       8      12       6      21       9      69       8       7     818      16]   83.984% 	[class: 9]
 [      10       7       1   

<trainer> on training set:	
<trainer> online epoch # 6 [batchSize = 100]	


Progress: 28301 / 60000	


<trainer> time to learn 1 sample = 0.06148099899292ms	


ConfusionMatrix:
[[    5714       1      28      10      12      72      42       7      32       5]   96.471% 	[class: 1]
 [       2    6530      27      27       8      31       4      19      82      12]   96.856% 	[class: 2]
 [      35      57    5300      95      97      28      82      80     164      20]   88.956% 	[class: 3]
 [      23      31     113    5453       5     238      25      60     133      50]   88.941% 	[class: 4]
 [       8      25      41       6    5456       7      56      17      36     190]   93.393% 	[class: 5]
 [      71      34      54     184      65    4706      90      23     139      55]   86.811% 	[class: 6]
 [      38      16      60       1      68      76    5629       3      26       1]   95.117% 	[class: 7]
 [      24      16      83      22      60       8       2    5850      16     184]   93.376% 	[class: 8]
 [      32     110      73     150      28     174      44      18    5138      84]   87.814% 	[class: 9]
 [      32      32      21   

<trainer> saving network to /home/saurabh/Desktop/COGS 260/Project 2/saurabh/torch tutorial/Assignment 2/mnist.net	
<trainer> on testing Set:	


<trainer> time to test 1 sample = 0.032432103157043ms	
ConfusionMatrix:
[[     952       0       3       1       0      16       6       1       1       0]   97.143% 	[class: 1]
 [       0    1109       2       2       0       3       3       2      14       0]   97.709% 	[class: 2]
 [       9      10     906      15      11      13      13      11      39       5]   87.791% 	[class: 3]
 [       4       1      17     875       0      70       1      15      16      11]   86.634% 	[class: 4]
 [       1       2       9       1     895       4       8       4       7      51]   91.141% 	[class: 5]
 [       8       2       4      20       4     817      10       4      17       6]   91.592% 	[class: 6]
 [      12       3       7       1      12      38     882       2       1       0]   92.067% 	[class: 7]
 [       1       8      22       6       5       2       0     936       1      47]   91.051% 	[class: 8]
 [       8       9       6      21       9      61       9       7     829      

  _target : FloatTensor - empty
  unionvalids : FloatTensor - size: 10
  totalValid : 0.9129
}


<trainer> on training set:	
<trainer> online epoch # 7 [batchSize = 100]	


Progress: 24001 / 60000	


<trainer> time to learn 1 sample = 0.060520247618357ms	
ConfusionMatrix:
[[    5719       1      28      11      14      68      39       7      31       5]   96.556% 	[class: 1]
 [       2    6537      28      27       8      30       4      18      76      12]   96.959% 	[class: 2]
 [      37      57    5301      97      98      28      81      80     161      18]   88.973% 	[class: 3]
 [      23      30     115    5457       5     231      25      58     136      51]   89.007% 	[class: 4]
 [       7      26      39       5    5460       8      56      18      34     189]   93.461% 	[class: 5]
 [      65      34      54     181      64    4718      91      23     137      54]   87.032% 	[class: 6]
 [      37      15      59       2      70      75    5630       4      25       1]   95.133% 	[class: 7]
 [      24      15      79      23      59       8       2    5855      16     184]   93.456% 	[class: 8]
 [      32     108      72     149      26     170      46      19    5147     

<trainer> saving network to /home/saurabh/Desktop/COGS 260/Project 2/saurabh/torch tutorial/Assignment 2/mnist.net	
<trainer> on testing Set:	


<trainer> time to test 1 sample = 0.032783102989197ms	


ConfusionMatrix:
[[     955       0       2       1       0      15       5       1       1       0]   97.449% 	[class: 1]
 [       0    1108       2       2       0       3       4       2      14       0]   97.621% 	[class: 2]
 [       9      10     908      15      10      12      15       8      40       5]   87.984% 	[class: 3]
 [       4       1      17     880       0      66       1      14      17      10]   87.129% 	[class: 4]
 [       1       2       9       1     898       4       8       4       7      48]   91.446% 	[class: 5]
 [       9       2       4      20       5     813      12       4      17       6]   91.143% 	[class: 6]
 [      12       3       7       1      11      36     885       2       1       0]   92.380% 	[class: 7]
 [       1       8      22       6       5       2       0     933       1      50]   90.759% 	[class: 8]
 [       8      10       6      21       9      58       9       7     831      15]   85.318% 	[class: 9]
 [      10       8       1   

6 : 6
      7 : 7
      8 : 8
      9 : 9
      10 : 10
    }
  _prediction : FloatTensor - size: 10
  _pred_idx : LongTensor - size: 1
  nclasses : 10
  _max : FloatTensor - size: 1
  _target : FloatTensor - empty
  unionvalids : FloatTensor - size: 10
  totalValid : 0.9144
}


<trainer> on training set:	
<trainer> online epoch # 8 [batchSize = 100]	


Progress: 19701 / 60000	


<trainer> time to learn 1 sample = 0.061601869265238ms	
ConfusionMatrix:
[[    5717       1      27      12      11      69      42       7      32       5]   96.522% 	[class: 1]
 [       1    6537      27      28       8      30       4      16      79      12]   96.959% 	[class: 2]
 [      35      53    5314      98      98      26      78      80     158      18]   89.191% 	[class: 3]
 [      22      28     115    5466       4     230      25      56     135      50]   89.153% 	[class: 4]
 [       7      25      38       7    5473       7      54      17      33     181]   93.684% 	[class: 5]
 [      64      33      56     179      64    4731      89      23     131      51]   87.272% 	[class: 6]
 [      36      15      62       1      68      75    5633       4      23       1]   95.184% 	[class: 7]
 [      23      15      79      22      58       8       2    5863      17     178]   93.583% 	[class: 8]
 [      32     110      69     151      26     166      45      20    5153     

<trainer> saving network to /home/saurabh/Desktop/COGS 260/Project 2/saurabh/torch tutorial/Assignment 2/mnist.net	
<trainer> on testing Set:	


<trainer> time to test 1 sample = 0.033362698554993ms	
ConfusionMatrix:
[[     954       0       2       1       0      15       6       1       1       0]   97.347% 	[class: 1]
 [       0    1109       2       2       0       2       4       2      14       0]   97.709% 	[class: 2]
 [       9      10     909      15      11      11      14       8      40       5]   88.081% 	[class: 3]
 [       4       1      18     876       0      69       1      15      17       9]   86.733% 	[class: 4]
 [       0       2      10       1     903       3       7       4       6      46]   91.955% 	[class: 5]
 [       9       2       4      18       5     816      12       4      17       5]   91.480% 	[class: 6]
 [      12       3       7       1      11      34     887       2       1       0]   92.589% 	[class: 7]
 [       1       8      21       5       6       2       0     932       2      51]   90.661% 	[class: 8]
 [       8       9       6      21       9      57       9       7     833      

  4 : 4
      5 : 5
      6 : 6
      7 : 7
      8 : 8
      9 : 9
      10 : 10
    }
  _prediction : FloatTensor - size: 10
  _pred_idx : LongTensor - size: 1
  nclasses : 10
  _max : FloatTensor - size: 1
  _target : FloatTensor - empty
  unionvalids : FloatTensor - size: 10
  totalValid : 0.9152
}


<trainer> on training set:	
<trainer> online epoch # 9 [batchSize = 100]	


Progress: 14801 / 60000	


<trainer> time to learn 1 sample = 0.060054000218709ms	
ConfusionMatrix:
[[    5721       1      28      13      12      67      38       7      30       6]   96.590% 	[class: 1]
 [       1    6540      28      28       8      29       4      16      75      13]   97.004% 	[class: 2]
 [      36      55    5315     102      95      27      77      82     151      18]   89.208% 	[class: 3]
 [      23      29     115    5470       4     222      25      59     134      50]   89.219% 	[class: 4]
 [       7      25      37       7    5480       7      52      17      32     178]   93.803% 	[class: 5]
 [      64      33      58     177      63    4735      87      22     130      52]   87.346% 	[class: 6]
 [      35      15      61       1      66      73    5639       4      23       1]   95.286% 	[class: 7]
 [      24      14      78      22      59       7       2    5867      17     175]   93.647% 	[class: 8]
 [      32     110      69     156      24     169      45      18    5156     


  unionvalids : FloatTensor - size: 10
  totalValid : 0.92143333333333
}


<trainer> saving network to /home/saurabh/Desktop/COGS 260/Project 2/saurabh/torch tutorial/Assignment 2/mnist.net	
<trainer> on testing Set:	


<trainer> time to test 1 sample = 0.034553098678589ms	


ConfusionMatrix:
[[     956       0       2       1       0      14       5       1       1       0]   97.551% 	[class: 1]
 [       0    1110       2       2       0       1       4       2      14       0]   97.797% 	[class: 2]
 [       9      10     909      15      12      11      13       8      40       5]   88.081% 	[class: 3]
 [       4       1      19     878       0      67       1      15      16       9]   86.931% 	[class: 4]
 [       0       3      10       1     900       3       7       4       6      48]   91.650% 	[class: 5]
 [      10       2       3      18       5     816      13       4      16       5]   91.480% 	[class: 6]
 [      12       3       7       1      11      32     889       2       1       0]   92.797% 	[class: 7]
 [       1       8      21       5       6       2       0     932       2      51]   90.661% 	[class: 8]
 [       8      10       6      22       9      57       9       7     831      15]   85.318% 	[class: 9]
 [      10       8       1   

<trainer> on training set:	
<trainer> online epoch # 10 [batchSize = 100]	


Progress: 10801 / 60000	


<trainer> time to learn 1 sample = 0.06085033416748ms	
ConfusionMatrix:
[[    5717       1      30      10      12      70      38       7      32       6]   96.522% 	[class: 1]
 [       1    6540      27      28       8      29       4      16      76      13]   97.004% 	[class: 2]
 [      36      55    5329     101      93      25      77      78     145      19]   89.443% 	[class: 3]
 [      22      28     117    5481       4     217      25      55     134      48]   89.398% 	[class: 4]
 [       9      25      39       6    5478       7      49      16      33     180]   93.769% 	[class: 5]
 [      64      33      56     175      62    4739      88      21     130      53]   87.419% 	[class: 6]
 [      35      15      64       1      64      75    5638       3      22       1]   95.269% 	[class: 7]
 [      23      15      79      22      60       7       2    5870      16     171]   93.695% 	[class: 8]
 [      32     108      72     153      24     165      46      18    5160      

unionvalids : FloatTensor - size: 10
  totalValid : 0.92196666666667
}


<trainer> saving network to /home/saurabh/Desktop/COGS 260/Project 2/saurabh/torch tutorial/Assignment 2/mnist.net	
<trainer> on testing Set:	


<trainer> time to test 1 sample = 0.033017492294312ms	


ConfusionMatrix:
[[     956       0       2       1       0      14       5       1       1       0]   97.551% 	[class: 1]
 [       0    1110       2       2       0       1       4       2      14       0]   97.797% 	[class: 2]
 [      10      10     910      15      11      10      13       8      40       5]   88.178% 	[class: 3]
 [       4       1      19     878       0      65       1      15      18       9]   86.931% 	[class: 4]
 [       0       3      10       1     902       3       7       4       7      45]   91.853% 	[class: 5]
 [      10       2       2      18       5     815      13       4      18       5]   91.368% 	[class: 6]
 [      12       3       8       1      10      33     888       2       1       0]   92.693% 	[class: 7]
 [       1       8      21       5       6       3       0     934       1      49]   90.856% 	[class: 8]
 [       8      10       6      21       9      57       9       7     832      15]   85.421% 	[class: 9]
 [      10       8       1   

In [2]:
test(testData, true)

<trainer> on testing Set:	


<trainer> time to test 1 sample = 0.036996293067932ms	
ConfusionMatrix:
[[     956       0       2       1       0      14       5       1       1       0]   97.551% 	[class: 1]
 [       0    1110       2       2       0       1       4       2      14       0]   97.797% 	[class: 2]
 [      10      10     910      15      11      10      13       8      40       5]   88.178% 	[class: 3]
 [       4       1      19     878       0      65       1      15      18       9]   86.931% 	[class: 4]
 [       0       3      10       1     902       3       7       4       7      45]   91.853% 	[class: 5]
 [      10       2       2      18       5     815      13       4      18       5]   91.368% 	[class: 6]
 [      12       3       8       1      10      33     888       2       1       0]   92.693% 	[class: 7]
 [       1       8      21       5       6       3       0     940       1      49]   90.909% 	[class: 8]
 [       8      10       6      21       9      57       9       7     832      

4 : 4
      5 : 5
      6 : 6
      7 : 7
      8 : 8
      9 : 9
      10 : 10
    }
  _prediction : FloatTensor - size: 10
  _pred_idx : LongTensor - size: 1
  nclasses : 10
  _max : FloatTensor - size: 1
  _target : FloatTensor - empty
  unionvalids : FloatTensor - size: 10
  totalValid : 0.91585048970618
}

